### ISSUE TITLE
Create Pipeline to automatically delete user accessible dummy database

### ISSUE THREAD

**Issue by EDGI9** [EDGI9/tv-show-app#35]
Script:
Adapt and remove Cron dependency

```
// clean-db.js

import { MongoClient } from 'mongodb';
import cron from 'node-cron';

// Connection URI and Database name
const uri = process.env.MONGO_URI || 'mongodb://localhost:27017'; // Change to your MongoDB URI
const dbName = 'your_database_name'; // Replace with your database name
const collectionName = 'your_collection_name'; // Replace with your collection name

// Define how old a document must be to be deleted
const DAYS_OLD = 30; // Customize this to your needs

// Connect to MongoDB
async function connectToMongo() {
  const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true });
  try {
    await client.connect();
    console.log('Connected to MongoDB');
    return client;
  } catch (err) {
    console.error('Failed to connect to MongoDB', err);
    return null;
  }
}

// Cleaning logic
async function cleanDatabase() {
  const client = await connectToMongo();
  if (!client) return;

  const db = client.db(dbName);
  const collection = db.collection(collectionName);

  // Define the date threshold
  const dateThreshold = new Date();
  dateThreshold.setDate(dateThreshold.getDate() - DAYS_OLD);

  // Delete documents older than the threshold
  try {
    const result = await collection.deleteMany({ createdAt: { $lt: dateThreshold } });
    console.log(`${result.deletedCount} documents deleted.`);
  } catch (err) {
    console.error('Error while cleaning the database', err);
  } finally {
    await client.close();
  }
}

// Schedule the task to run at midnight every day
cron.schedule('0 0 * * *', () => {
  console.log('Running database cleaning job');
  cleanDatabase();
});
```

Pipeline
1. Create a GitHub Actions Workflow
In your repository, create a .github/workflows/clean-db.yml file:

```
name: Clean MongoDB Database

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'

jobs:
  clean-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Run the cleaning script
        run: node server/clean-db.js

      - name: Post-cleanup log
        run: echo "MongoDB cleanup completed!"
```
2. Set Up Secrets for MongoDB Connection
Since GitHub Actions need to access your MongoDB instance, you should set the MongoDB URI as a secret in GitHub Actions:

Go to your GitHub repository settings.
Under the "Secrets and variables" section, add a new secret called MONGO_URI.
In your workflow, load this secret:

```
      - name: Run the cleaning script
        run: MONGO_URI=${{ secrets.MONGO_URI }} node server/clean-db.js
```

3. Schedule Execution via GitHub Actions
This setup will run the MongoDB cleaning script as scheduled (e.g., daily at midnight), without requiring manual triggering. The cleaning will be done in the GitHub-hosted environment.
